{{- if .Values.autoscaling.hpaEnabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "apache-nifi.fullname" . }}-hpa
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ template "apache-nifi.fullname" . }}
  minReplicas: {{ .Values.autoscaling.hpaMinReplicaCount }}
  maxReplicas: {{ .Values.autoscaling.hpaMaxReplicaCount }}
  metrics:
{{ toYaml .Values.autoscaling.metrics | indent 4 }}
  behavior:
{{ toYaml .Values.autoscaling.behavior | indent 4 }}  
{{- end }}
